### PR TITLE
FIx code issues from PE-D

### LINKED ISSUE #220: [PE-D][Tester D] `findperson` by region is case-sensitive
Description: `findperson` by region is case sensitive for no good reason. There are only 5 choices, `N`, `NE`, `W`, `E` and `C`. The case-insensitive version should also be allowed.

---

Impact: Negligible but there is some inconvenience for users

---

Suggestion: When validating the input, turn all to `UPPERCASE` or `LOWERCASE`.

---

Steps to reproduce:
1. Type `findperson ne` or use any of the regions in `LOWERCASE`.

Expected: Accept lowercase inputs

Actual:

Image

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`

### LINKED ISSUE #223: [PE-D][Tester D] `findorder r/` silently filters to active orders only, contradicting the UG
Description: When I use the `findorder r/` command, the UG states that I will "Finds all orders whose customer’s region matches the given region". But all orders are not found. Only then `Pending` orders are shown.

---

Impact: Users may be slightly misguided

---

Suggestion: Update the UG to reflect the correct behavior

---

Steps to reproduce:
1. Ensure the there is a customer in `INDEX` 1.
2. Type `addorder c/1 o/1 1`
3. Type `addorder c/1 o/1 1`
4. Type `complete 1`
5. Type `findorder r/E`. Take note that the region ,`E`, you type here should match with customer INDEX 1's region as my customers might be different.

Expected: Find all orders whose customer's region matches the given region

Actual: The customer `Alex Yeoh`'s completed orders are not shown even though he is in the `E` region.

Image

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`

### LINKED ISSUE #235: [PE-D][Tester D] `findorder` does not match the behavior stated in the UG
Description: The UG states that `findorder r/REGION` will "Finds all orders whose customer’s region matches the given region.". The UG constantly uses terms like all orders or active orders. My assumption is active orders are `Pending` while all orders means both `Pending` and `Completed`. Yet, the `findorder r/REGION` finds only active orders. Not all orders as stated in the UG.

---

Impact: Slight confusion for users using this command

---

Suggestion: Update the `findorder r/REGION` to find for `all orders` or update the UG to reflect that it only finds active orders.

---

Steps to reproduce:
1. Ensure that there is a customer at `INDEX` 1 and 2. Make sure both customers are from the same `REGION`
2. Type `addorder c/1 o/1 2`
3. Type `complete 1`
4. Type `addorder c/2 o/1 3`.
5. Type `findorder r/E`. Make sure the `REGION` matches both customer else this will fail in reproducing the bug.

Expected: As per the UG, I should "Finds all orders whose customer’s region matches the given region"

Actual: I only see the `Pending` orders from that region. No `Completed` orders can be seen even though I just marked one as complete.

Image

-------------
Labels: `severity.Low` `type.DocumentationBug`

### LINKED ISSUE #238: [PE-D][Tester B] findperson rejects lowercase regions although UG says search is case-insensitive
### Summary
The User Guide states that findperson is case-insensitive (e.g., n matches N), but the parser only accepts uppercase region tokens. This creates a user-visible UG-feature mismatch.

### Steps to reproduce
1. Launch the app.
2. Enter: findperson n

### Actual result
Command is rejected as invalid region input.

### Expected result
Command should be accepted and behave equivalently to findperson N.

### Severity justification
The UG explicitly promises case-insensitive behavior, so this mismatch is misleading and causes avoidable command failures.

### Evidence
Image

-------------
Labels: `severity.Low` `type.DocumentationBug`

### LINKED ISSUE #240: [PE-D][Tester B] findorder p/ includes completed orders while findorder r/ only shows active orders
### Summary
Filtering by region returns only pending orders, while filtering by phone matches orders regardless of status. This is inconsistent behavior within the same command and conflicts with DG wording that describes finding active orders by phone or region.

### Steps to reproduce
1. Ensure there is at least one order for phone 98765432.
2. Mark one of that phone's orders as completed using complete INDEX.
3. Enter: findorder p/98765432
4. Enter: findorder r/<that customer's region>

### Actual result
findorder p/98765432 includes completed orders, but findorder r/... excludes completed orders.

### Expected result
Both filters in findorder should apply status consistently (either both include all statuses or both show only active orders), aligned with the documented behavior.

### Severity justification
Inconsistent filtering logic can mislead delivery planning and produce unexpected results, though the app remains usable.

### Evidence
Image
Image

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by hahaahaahh**
### ✅ Behavior Updates

1. **`findorder r/REGION` is now case-insensitive**
   - Lowercase inputs like `findorder r/n` are accepted and treated the same as `findorder r/N`.

2. **`findorder r/REGION` now returns both pending and completed orders**
   - Region filtering no longer limits results to only pending orders.
   - Cancelled orders remain excluded.

---

### ✅ Implementation Changes

- **`src/main/java/seedu/address/logic/parser/order/FindOrderByPredicateCommandParser.java`**
  - Region input is normalized with `toUpperCase()` before parsing in the `r/` branch.

- **`src/main/java/seedu/address/model/order/RegionPredicate.java`**
  - Predicate logic changed from:
    - `status == PENDING`
  - to:
    - `status != CANCELLED`
  - Effect: includes **PENDING + COMPLETED**, excludes **CANCELLED**.

- **`src/main/java/seedu/address/logic/commands/order/FindOrderByRegionCommand.java`**
  - Command comments/docstrings updated to match new semantics (non-cancelled region orders).

---

### ✅ Test Updates

- **`src/test/java/seedu/address/logic/parser/order/FindOrderByPredicateCommandParserTest.java`**
  - Added success case for lowercase region input:
    - `r/n` parses successfully.

- **`src/test/java/seedu/address/model/order/RegionPredicateTest.java`**
  - Updated expectation: completed orders in matching region now return `true`.
  - Added cancelled-order test to ensure cancelled orders are still excluded.
  - Existing region-match / region-mismatch tests remain valid.

---

### ✅ Result

The `findorder` command now supports more user-friendly region input and shows a fuller regional order view (pending + completed), while preserving exclusion of cancelled orders.

Closes #240. Closes #238. Closes #235. Closes #223. Closes #220.

### CODE REVIEW

File: src/main/java/seedu/address/model/order/RegionPredicate.java [hunk 1]
```diff
@@ -18,7 +18,7 @@ public RegionPredicate(Region region) {
     @Override
     public boolean test(OrderMap order) {
         return order.getPerson().getRegion().equals(region)
-                && order.getStatus() == OrderStatus.PENDING;
+                && order.getStatus() != OrderStatus.CANCELLED;
```
Comment (lucas-wyd) [inline src/main/java/seedu/address/model/order/RegionPredicate.java:21]: better to delete this condition instead of changing to Cancelled

File: src/main/java/seedu/address/logic/commands/order/FindOrderByRegionCommand.java [hunk 2]
```diff
@@ -10,15 +10,15 @@
 import seedu.address.model.order.RegionPredicate;
 
 /**
- * Finds and lists all active orders in address book whose customer's region matches the given region.
```
Comment (lucas-wyd) [inline src/main/java/seedu/address/logic/commands/order/FindOrderByRegionCommand.java:13]: update this and test also
