### PR TITLE
Fix: editperson bugs

### LINKED ISSUE #129: Bug: Usage message of editperson not completely up to date
Steps to reproduce:
Use `editperson`

The message still shows order as one of the parameters
Image

The example message also shows orders as the parameter
Image

### LINKED ISSUE #151: Test feedback for `editperson` feature
**Bugs:**
- Wrong error message for invalid unit (shows postal code error instead of unit error)
Image

**Suggestions:**
- Maybe change the duplicate name error message to duplicate phone number message instead?
Image

### PR DESCRIPTION
**Pull request by select-e**
Closes #151. Closes #129

1. Used correct unit number error message:

Screenshot 2026-04-05 at 11 53 45 AM

2. Changed duplicate name check to duplicate phone number check:

Screenshot 2026-04-05 at 11 46 50 AM

3. Removed order references from the usage message:

Screenshot 2026-04-05 at 11 56 48 AM

### CODE REVIEW

**Comment by hahaahaahh** [comment]
LGTM:)

File: src/test/java/seedu/address/model/person/PersonTest.java [hunk 1]
```diff
@@ -31,23 +31,14 @@ public void isSamePerson() {
         // null -> returns false
         assertFalse(ALICE.isSamePerson(null));
 
-        // same name, all other attributes different -> returns true
-        Person editedAlice = new PersonBuilder(ALICE).withPhone(VALID_PHONE_BOB)
+        // same phone number, all other attributes different -> returns false
```
Comment (Achiack) [inline src/test/java/seedu/address/model/person/PersonTest.java]: Should this comment be return true instead of return false? Other than this the rest LGTM.
