### PR TITLE
Fix: address the suggestions and bugs in alpha test for `findperson` and `listorder` command and also make the order list UI friendlier for users

### LINKED ISSUE #121: Bug: findperson command accepts keywords that are not regions
E.g. `findperson x`, `findperson s`, `findperson alex` are accepted as valid parameters, even though they are not regions. It results in 0 persons being displayed:

Image

For better validation and feedback, it would be good to change it so that the command only accepts one of the five regions.

### LINKED ISSUE #124: Bug: findperson command does not detect invalid inputs
e.g. `findperson North`, `findperson alsdkjvn`, `findperson abc` will show "0 persons listed". An error message should be displayed. 

Image

### LINKED ISSUE #125: Suggestion: Add a separator between each item on the OrderCard
Image

"Ice Cream x2 Caesar Salad x1", add a separator for easier readability: "Ice Cream x2, Caesar Salad x1"

### LINKED ISSUE #126: Suggestion: Display region on the OrderCard
When the delivery worker views orders, it might be useful to see where the orders should be delivered at a glance, rather than having to cross-reference the contact.

### LINKED ISSUE #139: Test: feedback for `listing all orders` by Yida
# Summary

## Bugs:
- the time of the order is not shown. as user friendly format:

Image

## Suggestions:
- now the customer name is at the heading of each order item, but for an order item the person's name might not be that important and user might get confused when person list and order list both use name as headings. consider to align the font size of each component of an order item or uses the orderMaps as headings

Image

- consider highlight the status of the order just like what `tag` looks like in person list
- consider put the newest added order at the top of the list otherwise if the list are long, user might need to scroll down to find the order added
- the phone number of the person of an order item is not shown, it might be strange to filter by phone number with phone number not shown in the list

### PR DESCRIPTION
**Pull request by hahaahaahh**
### `findperson`
- Added validation for region keywords (`N`, `NE`, `W`, `E`, `C`) so invalid input throws a clear error message.
- Parser now reports `Region.MESSAGE_CONSTRAINTS` when given unsupported regions.
- Tests updated to cover invalid region input.

### `listorder` 
- Order cards were updated to show the customer’s region and improve item readability with comma‑separated items.
- Adapt order list UI to display time friendlier.
- Alter order list sequence to be according to time.

Closes #121. Closes #124. Closes #125. Closes #126. Closes #139.

### CODE REVIEW

File: src/main/java/seedu/address/ui/OrderCard.java [hunk 1]
```diff
@@ -42,16 +47,34 @@ public OrderCard(OrderMap order, int displayedIndex) {
         this.order = order;
         id.setText(displayedIndex + ". ");
         customer.setText(order.getPerson().getName().fullName);
-        region.setText("Region: " + order.getPerson().getRegion());
-        status.setText("Status: " + order.getStatus());
-        datetime.setText("At: " + order.getOrderDatetime());
+        region.setText(order.getPerson().getRegion().toLabel());
+        region.setStyle("-fx-background-color: " + order.getPerson().getRegion().getColour());
+        datetime.setText("At: " + order.getOrderDatetime().value.format(DISPLAY_FORMATTER));
```
Comment (yellowbrickkode) [inline src/main/java/seedu/address/ui/OrderCard.java]: i think the there's a function in OrderDateTime.java that formats it neatly, you could use that instead :)

**Comment by WANG-YIDA** [comment]
> The current order list looks like this: 4225d0ba-9e4b-46a0-b6c3-b49918d9c156 @WANG-YIDA

LGTM
